name: Check in
# Controls when the workflow will run
on:
  schedule:
    - cron: '40 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  check-in:
    name: Check in
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stu:
          - stu_num: '23182105'
            address: '中国北京市海淀区花园路街道校园东路18号'
    steps:
      - name: Send request
        continue-on-error: true
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 5
          max_attempts: 30
          retry_wait_seconds: 60
          command: |
            curl https://bjxyxsxx.buaa.edu.cn/bjxy/qdqj/addQdInfo.do -X POST -F stuNum=${{ matrix.stu.stu_num }} -F key= -F address=${{ matrix.stu.address }}
